#include "catalog/hyg/HygCatalogParser.hpp"
#include "catalog/normalize/CatalogParsingUtilities.hpp"
#include "catalog/io/DelimitedCatalogParser.hpp"

#include <QString>
#include <QStringView>

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>
#include <utility>

namespace skygate::ephemeris {
namespace {

constexpr std::size_t kHygRowCountLimitFloor = 2000000;
constexpr std::size_t kHygMinExpectedBytesPerDataRow = 6;
constexpr double kMasPerArcsecond = 1'000.0;
constexpr double kHygMissingDistanceParsecs = 100'000.0;

[[nodiscard]] AstronomicalEpoch j2000CatalogEpoch() noexcept
{
    return {
        .julianDatePart1 = 2'451'545.0,
        .julianDatePart2 = 0.0,
        .timeScale = TimeScale::Tt,
    };
}

[[nodiscard]] std::optional<double> optionalFiniteDoubleColumn(const DelimitedCatalogRow& row, const QString& name)
{
    const QString text = row.decodeColumn(name);
    if (text.trimmed().isEmpty()) {
        return std::nullopt;
    }

    return CatalogParsingUtilities::parseFiniteDouble(QStringView{text});
}

[[nodiscard]] std::optional<double> parallaxMasFromHygRow(const DelimitedCatalogRow& row)
{
    if (const std::optional<double> parallaxMas = optionalFiniteDoubleColumn(row, QStringLiteral("parallax"));
        parallaxMas.has_value()) {
        return parallaxMas;
    }
    if (const std::optional<double> parallaxMas = optionalFiniteDoubleColumn(row, QStringLiteral("plx"));
        parallaxMas.has_value()) {
        return parallaxMas;
    }
    if (const std::optional<double> distanceParsecs = optionalFiniteDoubleColumn(row, QStringLiteral("dist"));
        distanceParsecs.has_value() && *distanceParsecs > 0.0 && *distanceParsecs < kHygMissingDistanceParsecs) {
        return kMasPerArcsecond / *distanceParsecs;
    }

    return std::nullopt;
}

constexpr std::string_view kHygInvalidCategoryLabels[] = {
    "invalid numeric values",
};

}  // namespace

CatalogBodyParseResult
HygCatalogParser::parse(const std::string_view csvData, const HygParseProgressCallback& progressCallback) const
{
    std::size_t autoGeneratedIdCounter = 1;

    return DelimitedCatalogParser::run(
        csvData,
        DelimitedCatalogReaderOptions{
            .separator = ',',
            .requiredColumns =
                {
                    QStringLiteral("ra"),
                    QStringLiteral("dec"),
                    QStringLiteral("mag"),
                },
            .invalidErrorCode = CatalogLoadResult::ErrorCode::InvalidHygCsv,
            .rowCountLimitFloor = kHygRowCountLimitFloor,
            .minExpectedBytesPerDataRow = kHygMinExpectedBytesPerDataRow,
            .emptyInputDetail = "HYG CSV payload is empty.",
            .missingColumnsDetail = "HYG CSV payload is missing one of the required columns: ra, dec, mag.",
            .rowLimitDetail = "HYG CSV payload exceeds the supported row limit.",
        },
        DelimitedCatalogParserOptions{
            .zeroResultCode = CatalogLoadResult::ErrorCode::InvalidHygCsv,
            .zeroResultDetail = "HYG CSV payload does not contain any valid star rows.",
            .formatName = "HYG CSV",
        },
        kHygInvalidCategoryLabels,
        [&](const DelimitedCatalogRow& row, std::size_t rowNumber) -> RowParseOutcome {
            const QString raText = row.decodeColumn(QStringLiteral("ra"));
            const QString decText = row.decodeColumn(QStringLiteral("dec"));
            const QString magText = row.decodeColumn(QStringLiteral("mag"));
            const auto raHours = CatalogParsingUtilities::parseFiniteDouble(QStringView{raText});
            const auto decDeg = CatalogParsingUtilities::parseFiniteDouble(QStringView{decText});
            const auto magnitude = CatalogParsingUtilities::parseFiniteDouble(QStringView{magText});
            if (!raHours.has_value() || !decDeg.has_value() || !magnitude.has_value()) {
                return RowParseOutcome{
                    .invalidCategoryIndex = 0,
                    .invalidSample =
                        QStringLiteral("row %1 ra='%2' dec='%3' mag='%4'")
                            .arg(QString::number(static_cast<qulonglong>(rowNumber + 1U)), raText, decText, magText),
                };
            }

            const QString idField = row.decodeColumn(QStringLiteral("id"));
            const QString properName = row.decodeColumn(QStringLiteral("proper"));
            const QString bayerFlamsteed = row.decodeColumn(QStringLiteral("bf"));
            const QString hip = row.decodeColumn(QStringLiteral("hip"));

            CelestialBody body;
            body.type = CelestialBodyType::Star;
            body.visualMagnitude = *magnitude;
            body.fixedEquatorial =
                core::EquatorialCoordinate{.rightAscensionHours = *raHours, .declinationDeg = *decDeg};

            CatalogStarAstrometry astrometry;
            astrometry.referenceEquatorial = *body.fixedEquatorial;
            astrometry.referenceEpoch = j2000CatalogEpoch();
            astrometry.properMotionRightAscensionMasPerYear = optionalFiniteDoubleColumn(row, QStringLiteral("pmra"));
            astrometry.properMotionDeclinationMasPerYear = optionalFiniteDoubleColumn(row, QStringLiteral("pmdec"));
            astrometry.stellarParallaxMas = parallaxMasFromHygRow(row);
            astrometry.radialVelocityKmPerSecond = optionalFiniteDoubleColumn(row, QStringLiteral("rv"));
            if (astrometry.properMotionRightAscensionMasPerYear.has_value()
                || astrometry.properMotionDeclinationMasPerYear.has_value() || astrometry.stellarParallaxMas.has_value()
                || astrometry.radialVelocityKmPerSecond.has_value()) {
                body.starAstrometry = astrometry;
            }

            if (!hip.isEmpty()) {
                body.id = "hip_" + CatalogParsingUtilities::toUtf8String(hip);
            } else if (!idField.isEmpty()) {
                body.id = "hyg_" + CatalogParsingUtilities::toUtf8String(idField);
            } else {
                body.id = "hyg_auto_" + std::to_string(autoGeneratedIdCounter++);
            }

            if (!properName.isEmpty()) {
                body.displayName = CatalogParsingUtilities::toUtf8String(properName);
            } else if (!bayerFlamsteed.isEmpty()) {
                body.displayName = CatalogParsingUtilities::toUtf8String(bayerFlamsteed);
            } else if (!hip.isEmpty()) {
                body.displayName = "HIP " + CatalogParsingUtilities::toUtf8String(hip);
            } else {
                body.displayName = body.id;
            }

            return RowParseOutcome{.body = std::move(body)};
        },
        progressCallback
    );
}

}  // namespace skygate::ephemeris
