#include "catalog/HygCatalogParser.hpp"

#include "catalog/CsvRowTokenizer.hpp"

#include <QByteArray>
#include <QHash>
#include <QString>
#include <QStringView>
#include <QVector>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <queue>
#include <string>
#include <utility>
#include <vector>

namespace skygate::ephemeris {
namespace {

constexpr std::size_t kMaxHygBodyCount = 25000;
constexpr std::size_t kHygProgressCallbackInterval = 512;
constexpr std::size_t kMinHygRowCountLimit = 2000000;
constexpr std::size_t kMinPlausibleHygRowBytes = 6;

struct BrightnessSlotEntry {
    double visualMagnitude = 0.0;
    std::size_t slotIndex = 0;
    std::uint64_t generation = 0;
};

struct DimmestFirstCompare {
    [[nodiscard]] bool operator()(
        const BrightnessSlotEntry& lhs,
        const BrightnessSlotEntry& rhs
    ) const noexcept
    {
        if (lhs.visualMagnitude == rhs.visualMagnitude) {
            return lhs.slotIndex < rhs.slotIndex;
        }
        return lhs.visualMagnitude < rhs.visualMagnitude;
    }
};

std::optional<double> parseFiniteDouble(const QStringView text)
{
    const QString trimmed = text.trimmed().toString();
    if (trimmed.isEmpty()) {
        return std::nullopt;
    }

    bool isDouble = false;
    const double value = trimmed.toDouble(&isDouble);
    if (!isDouble || !std::isfinite(value)) {
        return std::nullopt;
    }

    return value;
}

std::string toStdString(const QString& text)
{
    const QByteArray utf8 = text.toUtf8();
    return std::string(utf8.constData(), static_cast<std::size_t>(utf8.size()));
}

}  // namespace

std::vector<CelestialBody> HygCatalogParser::parse(
    const std::string_view csvData,
    const HygParseProgressCallback& progressCallback
) const
{
    constexpr qsizetype kMissingColumnIndex = -1;

    std::vector<CelestialBody> bodies;
    bodies.reserve(kMaxHygBodyCount);
    std::vector<std::uint64_t> slotGenerations;
    slotGenerations.reserve(kMaxHygBodyCount);
    std::priority_queue<
        BrightnessSlotEntry,
        std::vector<BrightnessSlotEntry>,
        DimmestFirstCompare
    > dimmestSelectedStars;

    const auto discardStaleHeapEntries = [&]() {
        while (!dimmestSelectedStars.empty()) {
            const BrightnessSlotEntry& topEntry = dimmestSelectedStars.top();
            if (topEntry.slotIndex >= bodies.size()) {
                dimmestSelectedStars.pop();
                continue;
            }
            if (slotGenerations[topEntry.slotIndex] != topEntry.generation) {
                dimmestSelectedStars.pop();
                continue;
            }
            break;
        }
    };

    std::size_t cursor = 0;
    const std::size_t maxAllowedRowCount = std::max(
        kMinHygRowCountLimit,
        (csvData.size() / kMinPlausibleHygRowBytes) + 1U
    );
    std::size_t autoGeneratedIdCounter = 1;
    std::size_t parsedObjectCount = 0;
    std::size_t processedRowCount = 0;
    bool hasHeader = false;
    QHash<QString, qsizetype> headerIndex;
    qsizetype idColumn = kMissingColumnIndex;
    qsizetype hipColumn = kMissingColumnIndex;
    qsizetype properColumn = kMissingColumnIndex;
    qsizetype bayerFlamsteedColumn = kMissingColumnIndex;
    qsizetype raColumn = kMissingColumnIndex;
    qsizetype decColumn = kMissingColumnIndex;
    qsizetype magColumn = kMissingColumnIndex;

    while (cursor < csvData.size()) {
        const std::size_t newline = csvData.find('\n', cursor);
        const std::size_t lineEnd = newline == std::string_view::npos ? csvData.size() : newline;
        const std::string_view rawLine = csvData.substr(cursor, lineEnd - cursor);
        const QString line = QString::fromUtf8(
            rawLine.data(),
            static_cast<qsizetype>(rawLine.size())
        ).trimmed();
        if (!line.isEmpty()) {
            const QVector<QStringView> columns = CsvRowTokenizer::splitColumns(QStringView {line});
            if (!hasHeader) {
                for (qsizetype i = 0; i < columns.size(); ++i) {
                    const QString header = CsvRowTokenizer::decodeField(columns.at(i)).trimmed().toLower();
                    if (!header.isEmpty()) {
                        headerIndex.insert(header, i);
                    }
                }

                const auto findColumnIndex = [&](const QString& name) -> qsizetype {
                    const auto it = headerIndex.constFind(name);
                    if (it == headerIndex.cend()) {
                        return kMissingColumnIndex;
                    }
                    return *it;
                };

                idColumn = findColumnIndex("id");
                hipColumn = findColumnIndex("hip");
                properColumn = findColumnIndex("proper");
                bayerFlamsteedColumn = findColumnIndex("bf");
                raColumn = findColumnIndex("ra");
                decColumn = findColumnIndex("dec");
                magColumn = findColumnIndex("mag");
                if (
                    raColumn == kMissingColumnIndex
                    || decColumn == kMissingColumnIndex
                    || magColumn == kMissingColumnIndex
                ) {
                    return {};
                }
                hasHeader = true;
            } else {
                ++processedRowCount;
                if (processedRowCount > maxAllowedRowCount) {
                    return {};
                }

                const auto decodeColumn = [&](const qsizetype columnIndex) -> QString {
                    if (columnIndex == kMissingColumnIndex || columnIndex >= columns.size()) {
                        return {};
                    }
                    return CsvRowTokenizer::decodeField(columns.at(columnIndex)).trimmed();
                };

                const QString raText = decodeColumn(raColumn);
                const QString decText = decodeColumn(decColumn);
                const QString magText = decodeColumn(magColumn);
                const auto raHours = parseFiniteDouble(QStringView {raText});
                const auto decDeg = parseFiniteDouble(QStringView {decText});
                const auto magnitude = parseFiniteDouble(QStringView {magText});
                if (raHours.has_value() && decDeg.has_value() && magnitude.has_value()) {
                    ++parsedObjectCount;
                    if (parsedObjectCount > maxAllowedRowCount) {
                        return {};
                    }
                    if (progressCallback && (parsedObjectCount % kHygProgressCallbackInterval) == 0U) {
                        progressCallback(parsedObjectCount);
                    }

                    const QString idField = decodeColumn(idColumn);
                    const QString properName = decodeColumn(properColumn);
                    const QString bayerFlamsteed = decodeColumn(bayerFlamsteedColumn);
                    const QString hip = decodeColumn(hipColumn);

                    CelestialBody body;
                    body.type = CelestialBodyType::Star;
                    body.visualMagnitude = *magnitude;
                    body.fixedEquatorial = core::EquatorialCoordinate {
                        .rightAscensionHours = *raHours,
                        .declinationDeg = *decDeg
                    };

                    if (!hip.isEmpty()) {
                        body.id = "hip_" + toStdString(hip);
                    } else if (!idField.isEmpty()) {
                        body.id = "hyg_" + toStdString(idField);
                    } else {
                        body.id = "hyg_auto_" + std::to_string(autoGeneratedIdCounter++);
                    }

                    if (!properName.isEmpty()) {
                        body.displayName = toStdString(properName);
                    } else if (!bayerFlamsteed.isEmpty()) {
                        body.displayName = toStdString(bayerFlamsteed);
                    } else if (!hip.isEmpty()) {
                        body.displayName = "HIP " + toStdString(hip);
                    } else {
                        body.displayName = body.id;
                    }

                    if (bodies.size() < kMaxHygBodyCount) {
                        const std::size_t slotIndex = bodies.size();
                        bodies.push_back(std::move(body));
                        slotGenerations.push_back(0);
                        dimmestSelectedStars.push(
                            BrightnessSlotEntry {
                                .visualMagnitude = bodies.back().visualMagnitude,
                                .slotIndex = slotIndex,
                                .generation = slotGenerations[slotIndex]
                            }
                        );
                    } else {
                        discardStaleHeapEntries();
                        if (dimmestSelectedStars.empty()) {
                            continue;
                        }

                        const BrightnessSlotEntry dimmestSelected = dimmestSelectedStars.top();
                        if (body.visualMagnitude >= dimmestSelected.visualMagnitude) {
                            continue;
                        }

                        dimmestSelectedStars.pop();
                        bodies[dimmestSelected.slotIndex] = std::move(body);
                        ++slotGenerations[dimmestSelected.slotIndex];
                        dimmestSelectedStars.push(
                            BrightnessSlotEntry {
                                .visualMagnitude = bodies[dimmestSelected.slotIndex].visualMagnitude,
                                .slotIndex = dimmestSelected.slotIndex,
                                .generation = slotGenerations[dimmestSelected.slotIndex]
                            }
                        );
                    }
                }
            }
        }

        if (newline == std::string_view::npos) {
            break;
        }
        cursor = newline + 1;
    }

    if (progressCallback) {
        progressCallback(parsedObjectCount);
    }

    return bodies;
}

}  // namespace skygate::ephemeris
