#include "catalog/HygCatalogParser.hpp"

#include "catalog/CsvRowTokenizer.hpp"

#include <QByteArray>
#include <QHash>
#include <QString>
#include <QStringView>
#include <QVector>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <optional>
#include <string>
#include <vector>

namespace skygate::ephemeris {
namespace {

constexpr std::size_t kHygProgressCallbackInterval = 512;
constexpr std::size_t kMinHygRowCountLimit = 2000000;
constexpr std::size_t kMinPlausibleHygRowBytes = 6;

std::optional<double> parseFiniteDouble(const QStringView text)
{
    const QString trimmed = text.trimmed().toString();
    if (trimmed.isEmpty()) {
        return std::nullopt;
    }

    bool isDouble = false;
    const double value = trimmed.toDouble(&isDouble);
    if (!isDouble || !std::isfinite(value)) {
        return std::nullopt;
    }

    return value;
}

std::string toStdString(const QString& text)
{
    const QByteArray utf8 = text.toUtf8();
    return std::string(utf8.constData(), static_cast<std::size_t>(utf8.size()));
}

}  // namespace

CatalogBodyParseResult HygCatalogParser::parse(
    const std::string_view csvData,
    const HygParseProgressCallback& progressCallback
) const
{
    constexpr qsizetype kMissingColumnIndex = -1;

    CatalogBodyParseResult result;
    if (csvData.empty()) {
        result.errorCode = CatalogLoadErrorCode::EmptyInput;
        result.errorDetail = "HYG CSV payload is empty.";
        return result;
    }

    std::size_t cursor = 0;
    const std::size_t maxAllowedRowCount = std::max(
        kMinHygRowCountLimit,
        (csvData.size() / kMinPlausibleHygRowBytes) + 1U
    );
    std::vector<CelestialBody> bodies;
    std::size_t autoGeneratedIdCounter = 1;
    std::size_t parsedObjectCount = 0;
    std::size_t processedRowCount = 0;
    bool hasHeader = false;
    QHash<QString, qsizetype> headerIndex;
    qsizetype idColumn = kMissingColumnIndex;
    qsizetype hipColumn = kMissingColumnIndex;
    qsizetype properColumn = kMissingColumnIndex;
    qsizetype bayerFlamsteedColumn = kMissingColumnIndex;
    qsizetype raColumn = kMissingColumnIndex;
    qsizetype decColumn = kMissingColumnIndex;
    qsizetype magColumn = kMissingColumnIndex;

    while (cursor < csvData.size()) {
        const std::size_t newline = csvData.find('\n', cursor);
        const std::size_t lineEnd = newline == std::string_view::npos ? csvData.size() : newline;
        const std::string_view rawLine = csvData.substr(cursor, lineEnd - cursor);
        const QString line = QString::fromUtf8(
            rawLine.data(),
            static_cast<qsizetype>(rawLine.size())
        ).trimmed();
        if (!line.isEmpty()) {
            const QVector<QStringView> columns = CsvRowTokenizer::splitColumns(QStringView {line});
            if (!hasHeader) {
                for (qsizetype i = 0; i < columns.size(); ++i) {
                    const QString header = CsvRowTokenizer::decodeField(columns.at(i)).trimmed().toLower();
                    if (!header.isEmpty()) {
                        headerIndex.insert(header, i);
                    }
                }

                const auto findColumnIndex = [&](const QString& name) -> qsizetype {
                    const auto it = headerIndex.constFind(name);
                    if (it == headerIndex.cend()) {
                        return kMissingColumnIndex;
                    }
                    return *it;
                };

                idColumn = findColumnIndex("id");
                hipColumn = findColumnIndex("hip");
                properColumn = findColumnIndex("proper");
                bayerFlamsteedColumn = findColumnIndex("bf");
                raColumn = findColumnIndex("ra");
                decColumn = findColumnIndex("dec");
                magColumn = findColumnIndex("mag");
                if (
                    raColumn == kMissingColumnIndex
                    || decColumn == kMissingColumnIndex
                    || magColumn == kMissingColumnIndex
                ) {
                    result.errorCode = CatalogLoadErrorCode::MissingRequiredColumns;
                    result.errorDetail = "HYG CSV payload is missing one of the required columns: ra, dec, mag.";
                    return result;
                }
                hasHeader = true;
            } else {
                ++processedRowCount;
                if (processedRowCount > maxAllowedRowCount) {
                    result.errorCode = CatalogLoadErrorCode::InvalidHygCsv;
                    result.errorDetail = "HYG CSV payload exceeds the supported row limit.";
                    return result;
                }

                const auto decodeColumn = [&](const qsizetype columnIndex) -> QString {
                    if (columnIndex == kMissingColumnIndex || columnIndex >= columns.size()) {
                        return {};
                    }
                    return CsvRowTokenizer::decodeField(columns.at(columnIndex)).trimmed();
                };

                const QString raText = decodeColumn(raColumn);
                const QString decText = decodeColumn(decColumn);
                const QString magText = decodeColumn(magColumn);
                const auto raHours = parseFiniteDouble(QStringView {raText});
                const auto decDeg = parseFiniteDouble(QStringView {decText});
                const auto magnitude = parseFiniteDouble(QStringView {magText});
                if (raHours.has_value() && decDeg.has_value() && magnitude.has_value()) {
                    ++parsedObjectCount;
                    if (parsedObjectCount > maxAllowedRowCount) {
                        result.errorCode = CatalogLoadErrorCode::InvalidHygCsv;
                        result.errorDetail = "HYG CSV payload exceeds the supported object limit.";
                        return result;
                    }
                    if (progressCallback && (parsedObjectCount % kHygProgressCallbackInterval) == 0U) {
                        progressCallback(parsedObjectCount);
                    }

                    const QString idField = decodeColumn(idColumn);
                    const QString properName = decodeColumn(properColumn);
                    const QString bayerFlamsteed = decodeColumn(bayerFlamsteedColumn);
                    const QString hip = decodeColumn(hipColumn);

                    CelestialBody body;
                    body.type = CelestialBodyType::Star;
                    body.visualMagnitude = *magnitude;
                    body.fixedEquatorial = core::EquatorialCoordinate {
                        .rightAscensionHours = *raHours,
                        .declinationDeg = *decDeg
                    };

                    if (!hip.isEmpty()) {
                        body.id = "hip_" + toStdString(hip);
                    } else if (!idField.isEmpty()) {
                        body.id = "hyg_" + toStdString(idField);
                    } else {
                        body.id = "hyg_auto_" + std::to_string(autoGeneratedIdCounter++);
                    }

                    if (!properName.isEmpty()) {
                        body.displayName = toStdString(properName);
                    } else if (!bayerFlamsteed.isEmpty()) {
                        body.displayName = toStdString(bayerFlamsteed);
                    } else if (!hip.isEmpty()) {
                        body.displayName = "HIP " + toStdString(hip);
                    } else {
                        body.displayName = body.id;
                    }

                    bodies.push_back(std::move(body));
                }
            }
        }

        if (newline == std::string_view::npos) {
            break;
        }
        cursor = newline + 1;
    }

    if (progressCallback) {
        progressCallback(parsedObjectCount);
    }

    if (!hasHeader) {
        result.errorCode = CatalogLoadErrorCode::EmptyInput;
        result.errorDetail = "HYG CSV payload is empty.";
        return result;
    }

    if (parsedObjectCount == 0U) {
        result.errorCode = CatalogLoadErrorCode::InvalidHygCsv;
        result.errorDetail = "HYG CSV payload does not contain any valid star rows.";
        result.diagnostics.processedRowCount = processedRowCount;
        return result;
    }

    result.bodies = std::move(bodies);
    result.diagnostics.processedRowCount = processedRowCount;
    result.diagnostics.parsedBodyCount = parsedObjectCount;
    return result;
}

}  // namespace skygate::ephemeris
