#include "catalog/HygCatalogParser.hpp"

#include "catalog/CatalogParsingUtilities.hpp"
#include "catalog/DelimitedCatalogReader.hpp"

#include <QString>
#include <QStringView>

#include <cstddef>
#include <string>
#include <utility>

namespace skygate::ephemeris {
namespace {

constexpr std::size_t kHygProgressCallbackInterval = 512;
constexpr std::size_t kMinHygRowCountLimit = 2000000;
constexpr std::size_t kMinPlausibleHygRowBytes = 6;

}  // namespace

CatalogBodyParseResult HygCatalogParser::parse(
    const std::string_view csvData,
    const HygParseProgressCallback& progressCallback
) const
{
    std::size_t autoGeneratedIdCounter = 1;
    std::size_t parsedObjectCount = 0;

    CatalogBodyParseResult result = DelimitedCatalogReader::read(
        csvData,
        DelimitedCatalogReaderOptions {
            .separator = ',',
            .requiredColumns = {
                QStringLiteral("ra"),
                QStringLiteral("dec"),
                QStringLiteral("mag"),
            },
            .invalidErrorCode = CatalogLoadErrorCode::InvalidHygCsv,
            .minRowCountLimit = kMinHygRowCountLimit,
            .minPlausibleRowBytes = kMinPlausibleHygRowBytes,
            .emptyInputDetail = "HYG CSV payload is empty.",
            .missingColumnsDetail = "HYG CSV payload is missing one of the required columns: ra, dec, mag.",
            .rowLimitDetail = "HYG CSV payload exceeds the supported row limit.",
        },
        [&](const DelimitedCatalogReader::Row& row, CatalogBodyParseResult& rowResult) {
            const QString raText = row.decodeColumn(QStringLiteral("ra"));
            const QString decText = row.decodeColumn(QStringLiteral("dec"));
            const QString magText = row.decodeColumn(QStringLiteral("mag"));
            const auto raHours = catalog_parsing::parseFiniteDouble(QStringView {raText});
            const auto decDeg = catalog_parsing::parseFiniteDouble(QStringView {decText});
            const auto magnitude = catalog_parsing::parseFiniteDouble(QStringView {magText});
            if (!raHours.has_value() || !decDeg.has_value() || !magnitude.has_value()) {
                return true;
            }

            ++parsedObjectCount;
            if (progressCallback && (parsedObjectCount % kHygProgressCallbackInterval) == 0U) {
                progressCallback(parsedObjectCount);
            }

            const QString idField = row.decodeColumn(QStringLiteral("id"));
            const QString properName = row.decodeColumn(QStringLiteral("proper"));
            const QString bayerFlamsteed = row.decodeColumn(QStringLiteral("bf"));
            const QString hip = row.decodeColumn(QStringLiteral("hip"));

            CelestialBody body;
            body.type = CelestialBodyType::Star;
            body.visualMagnitude = *magnitude;
            body.fixedEquatorial = core::EquatorialCoordinate {
                .rightAscensionHours = *raHours,
                .declinationDeg = *decDeg
            };

            if (!hip.isEmpty()) {
                body.id = "hip_" + catalog_parsing::toUtf8String(hip);
            } else if (!idField.isEmpty()) {
                body.id = "hyg_" + catalog_parsing::toUtf8String(idField);
            } else {
                body.id = "hyg_auto_" + std::to_string(autoGeneratedIdCounter++);
            }

            if (!properName.isEmpty()) {
                body.displayName = catalog_parsing::toUtf8String(properName);
            } else if (!bayerFlamsteed.isEmpty()) {
                body.displayName = catalog_parsing::toUtf8String(bayerFlamsteed);
            } else if (!hip.isEmpty()) {
                body.displayName = "HIP " + catalog_parsing::toUtf8String(hip);
            } else {
                body.displayName = body.id;
            }

            rowResult.bodies.push_back(std::move(body));
            return true;
        }
    );

    if (!result.isSuccess()) {
        return result;
    }

    if (progressCallback) {
        progressCallback(parsedObjectCount);
    }

    if (parsedObjectCount == 0U) {
        result.errorCode = CatalogLoadErrorCode::InvalidHygCsv;
        result.errorDetail = "HYG CSV payload does not contain any valid star rows.";
        return result;
    }

    result.diagnostics.parsedBodyCount = parsedObjectCount;
    return result;
}

}  // namespace skygate::ephemeris
